import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Jawbts Api',
  description: 'Generated by Next.js',
  icons: [
    {
      url: "https://cdn.jawbts.org/photos/logo.svg",
      type: "image/svg+xml",
      rel: "icon"
    }
  ]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
